# Auto-Generated by Django 3.0.8 on 2020-11-04 06:44

# Copyright 2020 Google LLC. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

'''
Autogenerated migration file.
'''

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('encrypted_display_name', models.BinaryField(blank=True, default=None, null=True)),
                ('notification_preference', models.CharField(blank=True, choices=[('D', 'Daily'), ('W', 'Weekly'), ('B', 'Bi-Weekly')], default=None, max_length=1, null=True)),
                ('last_engaged', models.DateTimeField(auto_now=True)),
                ('subscribed', models.BooleanField(default=False)),
                ('access_token', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('reviewed', models.BooleanField(default=False)),
            ],
        ),
    ]
